// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DBSClient is the client API for DBS service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DBSClient interface {
	Process(ctx context.Context, in *DBRequest, opts ...grpc.CallOption) (*DBResponse, error)
}

type dBSClient struct {
	cc grpc.ClientConnInterface
}

func NewDBSClient(cc grpc.ClientConnInterface) DBSClient {
	return &dBSClient{cc}
}

func (c *dBSClient) Process(ctx context.Context, in *DBRequest, opts ...grpc.CallOption) (*DBResponse, error) {
	out := new(DBResponse)
	err := c.cc.Invoke(ctx, "/kubertest.DBS/Process", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DBSServer is the server API for DBS service.
// All implementations must embed UnimplementedDBSServer
// for forward compatibility
type DBSServer interface {
	Process(context.Context, *DBRequest) (*DBResponse, error)
	mustEmbedUnimplementedDBSServer()
}

// UnimplementedDBSServer must be embedded to have forward compatible implementations.
type UnimplementedDBSServer struct {
}

func (UnimplementedDBSServer) Process(context.Context, *DBRequest) (*DBResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Process not implemented")
}
func (UnimplementedDBSServer) mustEmbedUnimplementedDBSServer() {}

// UnsafeDBSServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DBSServer will
// result in compilation errors.
type UnsafeDBSServer interface {
	mustEmbedUnimplementedDBSServer()
}

func RegisterDBSServer(s grpc.ServiceRegistrar, srv DBSServer) {
	s.RegisterService(&DBS_ServiceDesc, srv)
}

func _DBS_Process_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DBRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DBSServer).Process(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kubertest.DBS/Process",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DBSServer).Process(ctx, req.(*DBRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DBS_ServiceDesc is the grpc.ServiceDesc for DBS service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DBS_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "kubertest.DBS",
	HandlerType: (*DBSServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Process",
			Handler:    _DBS_Process_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "svc_db.proto",
}
