// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.17.3
// source: svc_db.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DBRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Client string `protobuf:"bytes,1,opt,name=client,proto3" json:"client,omitempty"`
	Orch   string `protobuf:"bytes,2,opt,name=orch,proto3" json:"orch,omitempty"`
}

func (x *DBRequest) Reset() {
	*x = DBRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_db_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBRequest) ProtoMessage() {}

func (x *DBRequest) ProtoReflect() protoreflect.Message {
	mi := &file_svc_db_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBRequest.ProtoReflect.Descriptor instead.
func (*DBRequest) Descriptor() ([]byte, []int) {
	return file_svc_db_proto_rawDescGZIP(), []int{0}
}

func (x *DBRequest) GetClient() string {
	if x != nil {
		return x.Client
	}
	return ""
}

func (x *DBRequest) GetOrch() string {
	if x != nil {
		return x.Orch
	}
	return ""
}

type DBResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Db   string `protobuf:"bytes,1,opt,name=db,proto3" json:"db,omitempty"`
	Data string `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *DBResponse) Reset() {
	*x = DBResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_svc_db_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DBResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DBResponse) ProtoMessage() {}

func (x *DBResponse) ProtoReflect() protoreflect.Message {
	mi := &file_svc_db_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DBResponse.ProtoReflect.Descriptor instead.
func (*DBResponse) Descriptor() ([]byte, []int) {
	return file_svc_db_proto_rawDescGZIP(), []int{1}
}

func (x *DBResponse) GetDb() string {
	if x != nil {
		return x.Db
	}
	return ""
}

func (x *DBResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_svc_db_proto protoreflect.FileDescriptor

var file_svc_db_proto_rawDesc = []byte{
	0x0a, 0x0c, 0x73, 0x76, 0x63, 0x5f, 0x64, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x09,
	0x6b, 0x75, 0x62, 0x65, 0x72, 0x74, 0x65, 0x73, 0x74, 0x22, 0x37, 0x0a, 0x09, 0x44, 0x42, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6f, 0x72, 0x63, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6f, 0x72,
	0x63, 0x68, 0x22, 0x30, 0x0a, 0x0a, 0x44, 0x42, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x64, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x64, 0x62,
	0x12, 0x12, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x32, 0x3f, 0x0a, 0x03, 0x44, 0x42, 0x53, 0x12, 0x38, 0x0a, 0x07, 0x50,
	0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x12, 0x14, 0x2e, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x74, 0x65,
	0x73, 0x74, 0x2e, 0x44, 0x42, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x15, 0x2e, 0x6b,
	0x75, 0x62, 0x65, 0x72, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x44, 0x42, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_svc_db_proto_rawDescOnce sync.Once
	file_svc_db_proto_rawDescData = file_svc_db_proto_rawDesc
)

func file_svc_db_proto_rawDescGZIP() []byte {
	file_svc_db_proto_rawDescOnce.Do(func() {
		file_svc_db_proto_rawDescData = protoimpl.X.CompressGZIP(file_svc_db_proto_rawDescData)
	})
	return file_svc_db_proto_rawDescData
}

var file_svc_db_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_svc_db_proto_goTypes = []interface{}{
	(*DBRequest)(nil),  // 0: kubertest.DBRequest
	(*DBResponse)(nil), // 1: kubertest.DBResponse
}
var file_svc_db_proto_depIdxs = []int32{
	0, // 0: kubertest.DBS.Process:input_type -> kubertest.DBRequest
	1, // 1: kubertest.DBS.Process:output_type -> kubertest.DBResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_svc_db_proto_init() }
func file_svc_db_proto_init() {
	if File_svc_db_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_svc_db_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_svc_db_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DBResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_svc_db_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_svc_db_proto_goTypes,
		DependencyIndexes: file_svc_db_proto_depIdxs,
		MessageInfos:      file_svc_db_proto_msgTypes,
	}.Build()
	File_svc_db_proto = out.File
	file_svc_db_proto_rawDesc = nil
	file_svc_db_proto_goTypes = nil
	file_svc_db_proto_depIdxs = nil
}
